### PR TITLE
Modify treasury and circulating supply calc

### PR DESCRIPTION
**Pull request by derekpierre**
`T circulating supply = All unlocked NU * 3.259 + All unlocked KEEP * 4.783 + staking rewards + treasury spend`

- Determining `staking rewards` i.e. total claimable staking rewards is made easier via the merkle distribution github repos PR that was merged and is now available: https://github.com/threshold-network/merkle-distribution/pull/57
- Future minted tokens can be reported separately, but no longer need to be considered in other calculations since these tokens are stored in a separate FutureRewards Proxy contract
- Determining Treasury spend is made easier since the treasury of T tokens are being transferred out of the Council multisig and into the Governor Bravo TimeLock Controller contract. Therefore, treasury spend is simply `1B T - <balance in TimeLock Controller Contract>`

### CODE REVIEW

**Comment by derekpierre** [comment]
Just submitted commit for hard coding balance in GB Timelock contract. The output of the endpoint is now:

```json
{
   "current_total_supply": 10515000000.0,
   "dao_treasury_supply": 700000000.0,
   "future_rewards_supply": 147929551.5581849,
   "est_circulating_supply": 8760316532.145777
}
```

**Review by mswilkison — APPROVED** [review]

**Comment by derekpierre** [comment]
Current result after updating to use council balance:
```json
{"current_total_supply": 10515000000.0, "dao_treasury_supply": 884469296.3445909, "future_rewards_supply": 147929551.5581849, "est_circulating_supply": 8575847235.8011875}
```

**Comment by beaurancourt** [comment]
circulating supply before this PR: `8723757953.179718`
circulating supply after  this PR: `8575847235.8011875`
delta: 147.9M tokens

from derek:

> the reason for the ~148M difference is because in the past overminted tokens (future rewards that weren't supposed to be claimable) were sitting in the council multisig. So we were correctly removing it in the old calc (working down). Future rewards are not part of circulating supply.

> However, these Future rewards were moved out of the council to a FutureRewards Proxy contract, https://etherscan.io/address/0xbe3e95Dc12C0aE3FAC264Bf63ef89Ec81139E3DF, at the end of February, https://etherscan.io/tx/0x84144f5da2ebc5e75dd4bc4cbe149c11790246f7ded0c57fa646d0325d17511d .  This means that the old code is now no longer subtracting that value i.e. overreporting. 

> The balance in the FutureRewards proxy is ~174M. However, ~27M of that was supposed to be transferred to the ClaimableRewards Proxy (contract for staking rewards that can be claimed), https://etherscan.io/address/0xec8183891331a845E2DCf5CD616Ee32736E2BAA4,  for February staking rewards but hasn't as yet.

> ~174M - ~27M = ~147M

So we were overreporting by ~147M tokens and this PR *also* fixes that.

I'm good to go here! At some point in the future, the tokens in the council multisig will be marked as circulating, and so we'll need another PR to fix that, but we should be correct for a while.

👍🏻

**Comment by derekpierre** [comment]
> At some point in the future, the tokens in the council multisig will be marked as circulating, and so we'll need another PR to fix that, but we should be correct for a while.

👍 - This fix will likely be done in the next week or so.

**Pull request merged**
